import { useState, useEffect, useCallback } from 'react';
import { Sparkles, Edit3, Save, AlertTriangle, Download, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { StatusBadge } from '@/components/Common/StatusBadge';
import type { QAStatus } from '@/types/radiology';
import { ReportEditor } from '@/components/Forms/ReportEditor';
import { ApprovalDialog } from '@/components/Forms/ApprovalDialog';
import { formatDate, formatTime } from '@/data/mockData';
import { cn } from '@/lib/utils';

interface ImpressionPanelProps {
  impression: string;
  findings: string;
  qaStatus: QAStatus;
  qaWarnings: string[];
  inferenceStatus?: string;
  inferenceSummary?: string;
  inferenceConfidence?: number;
  inferenceModelVersion?: string;
  inferenceJobId?: string;
  inferenceCompletedAt?: string;
  onImpressionChange: (text: string) => void;
  onGenerateImpression: () => Promise<void>;
  onApprove: (signature?: string) => void;
  onExportSr?: (format: 'json' | 'dicom') => void;
  isGenerating?: boolean;
}

export function ImpressionPanel({
  impression,
  findings,
  qaStatus,
  qaWarnings,
  inferenceStatus,
  inferenceSummary,
  inferenceConfidence,
  inferenceModelVersion,
  inferenceJobId,
  inferenceCompletedAt,
  onImpressionChange,
  onGenerateImpression,
  onApprove,
  onExportSr,
  isGenerating = false,
}: ImpressionPanelProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const hasInferenceResult = Boolean(
    inferenceSummary ||
    inferenceStatus ||
    inferenceModelVersion ||
    inferenceConfidence !== undefined ||
    inferenceCompletedAt
  );

  const resolvedInferenceStatus = inferenceStatus || (inferenceSummary ? 'finished' : undefined);
  const inferenceStatusLabel: Record<string, { label: string; className: string }> = {
    queued: { label: 'Wartet', className: 'bg-warning/10 text-warning border-warning/30' },
    started: { label: 'Laeuft', className: 'bg-info/10 text-info border-info/30' },
    finished: { label: 'Fertig', className: 'bg-success/10 text-success border-success/30' },
    failed: { label: 'Fehler', className: 'bg-destructive/10 text-destructive border-destructive/30' },
  };

  // Auto-generate impression when findings change and we haven't generated yet
  useEffect(() => {
    if (findings && findings.length > 50 && !impression && !hasAutoGenerated && !isGenerating) {
      const timer = setTimeout(() => {
        setHasAutoGenerated(true);
        onGenerateImpression();
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [findings, impression, hasAutoGenerated, isGenerating, onGenerateImpression]);

  const handleSave = useCallback(() => {
    setIsEditing(false);
  }, []);

  const handleRegenerate = useCallback(() => {
    onGenerateImpression();
  }, [onGenerateImpression]);

  const canApprove = impression && qaStatus !== 'fail' && !isGenerating;

  return (
    <div className="flex flex-col flex-1">
      {/* Header */}
      <div className="panel-header">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-semibold uppercase tracking-wide">Beurteilung</h3>
          <Badge variant="outline" className="bg-primary/10 text-primary border-primary/30 text-xs">
            <Sparkles className="h-3 w-3 mr-1" />
            KI-Entwurf
          </Badge>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => isEditing ? handleSave() : setIsEditing(true)}
          disabled={isGenerating}
        >
          {isEditing ? (
            <>
              <Save className="h-4 w-4 mr-1.5" />
              Speichern
            </>
          ) : (
            <>
              <Edit3 className="h-4 w-4 mr-1.5" />
              Bearbeiten
            </>
          )}
        </Button>
      </div>

      {/* QA Status */}
      <div className="px-4 py-2 border-b border-border flex items-center justify-between bg-panel-secondary/30">
        <StatusBadge status={qaStatus} size="sm" />
        {isGenerating && (
          <span className="text-xs text-muted-foreground flex items-center gap-1.5">
            <div className="w-3 h-3 border-2 border-primary border-t-transparent rounded-full spinner" />
            Generiere Beurteilung...
          </span>
        )}
      </div>

      {/* QA Warnings */}
      {qaWarnings.length > 0 && (
        <div className="px-4 py-2 bg-warning/5 border-b border-warning/20 space-y-1">
          {qaWarnings.map((warning, idx) => (
            <div key={idx} className="flex items-start gap-2 text-xs text-warning">
              <AlertTriangle className="h-3 w-3 mt-0.5 shrink-0" />
              <span>{warning}</span>
            </div>
          ))}
        </div>
      )}

      {/* Inference Result */}
      {hasInferenceResult && (
        <div className="px-4 py-2 border-b border-border bg-panel-secondary/20 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Inferenz Ergebnis
            </span>
            {resolvedInferenceStatus && inferenceStatusLabel[resolvedInferenceStatus] && (
              <Badge
                variant="outline"
                className={cn('text-[10px] px-1.5 py-0', inferenceStatusLabel[resolvedInferenceStatus].className)}
              >
                {inferenceStatusLabel[resolvedInferenceStatus].label}
              </Badge>
            )}
          </div>
          <div className="text-xs text-muted-foreground space-y-1">
            <div>Modell: {inferenceModelVersion || 'n/a'}</div>
            {inferenceConfidence !== undefined && (
              <div>Konfidenz: {Math.round(inferenceConfidence * 100)}%</div>
            )}
            {inferenceCompletedAt && (
              <div>
                Zeit: {formatDate(inferenceCompletedAt)} {formatTime(inferenceCompletedAt)}
              </div>
            )}
            {inferenceJobId && (
              <div>Job: {inferenceJobId.slice(0, 8)}...</div>
            )}
          </div>
          {inferenceSummary ? (
            <p className="text-sm text-foreground whitespace-pre-wrap">{inferenceSummary}</p>
          ) : (
            <p className="text-xs text-muted-foreground">Kein Ergebnis verfuegbar.</p>
          )}
        </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-hidden min-h-[200px]">
        {isEditing ? (
          <ReportEditor
            value={impression}
            onChange={onImpressionChange}
            placeholder="Die KI-generierte Beurteilung erscheint hier..."
            className="h-full min-h-[200px]"
            ariaLabel="Beurteilung Text"
          />
        ) : (
          <div className="h-full p-4 overflow-y-auto">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center h-full gap-4 text-muted-foreground">
                <div className="w-8 h-8 border-3 border-primary border-t-transparent rounded-full spinner" />
                <p className="text-sm">MedGemma analysiert den Befund...</p>
              </div>
            ) : impression ? (
              <p className="text-sm whitespace-pre-wrap leading-relaxed">{impression}</p>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                Die Beurteilung wird automatisch generiert, sobald der Befund ausreichend ist.
              </p>
            )}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-border bg-panel-secondary/30 space-y-2">
        <ApprovalDialog
          onConfirm={onApprove}
          disabled={!canApprove}
          triggerLabel="Freigeben & Abschliessen"
        />

        {onExportSr && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="w-full justify-between"
                disabled={!impression && !findings}
              >
                <span className="flex items-center">
                  <Download className="h-4 w-4 mr-1.5" />
                  DICOM SR exportieren
                </span>
                <ChevronDown className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-48">
              <DropdownMenuItem onClick={() => onExportSr('dicom')}>
                DICOM SR (Binary)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => onExportSr('json')}>
                DICOM SR (JSON)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}
        
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            className="flex-1"
            onClick={handleRegenerate}
            disabled={isGenerating || !findings}
          >
            <Sparkles className="h-4 w-4 mr-1.5" />
            Neu generieren
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="flex-1"
            onClick={handleSave}
            disabled={!impression}
          >
            <Save className="h-4 w-4 mr-1.5" />
            Als Entwurf speichern
          </Button>
        </div>
      </div>

      {/* Footer hint */}
      <div className="px-4 py-2 border-t border-border text-xs text-muted-foreground text-center">
        Ctrl+Enter zum Freigeben
      </div>
    </div>
  );
}
