import { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { Sparkles, Edit3, Save, AlertTriangle, Download, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { StatusBadge } from '@/components/Common/StatusBadge';
import type { ImageRef, QAStatus } from '@/types/radiology';
import { ReportEditor } from '@/components/Forms/ReportEditor';
import { ApprovalDialog } from '@/components/Forms/ApprovalDialog';
import { Switch } from '@/components/ui/switch';
import { formatDate, formatTime } from '@/data/mockData';
import { cn } from '@/lib/utils';

interface ImpressionPanelProps {
  impression: string;
  findings: string;
  qaStatus: QAStatus;
  qaWarnings: string[];
  inferenceStatus?: string;
  inferenceSummary?: string;
  inferenceConfidence?: number;
  inferenceModelVersion?: string;
  inferenceJobId?: string;
  inferenceCompletedAt?: string;
  inferenceImageRefs?: ImageRef[];
  onEvidenceSelect?: (ref: ImageRef) => void;
  useAllFrames?: boolean;
  onUseAllFramesChange?: (nextValue: boolean) => void;
  onImpressionChange: (text: string) => void;
  onGenerateImpression: () => Promise<void>;
  onApprove: (signature?: string) => void;
  onExportSr?: (format: 'json' | 'dicom') => void;
  isGenerating?: boolean;
}

export function ImpressionPanel({
  impression,
  findings,
  qaStatus,
  qaWarnings,
  inferenceStatus,
  inferenceSummary,
  inferenceConfidence,
  inferenceModelVersion,
  inferenceJobId,
  inferenceCompletedAt,
  inferenceImageRefs,
  onEvidenceSelect,
  useAllFrames,
  onUseAllFramesChange,
  onImpressionChange,
  onGenerateImpression,
  onApprove,
  onExportSr,
  isGenerating = false,
}: ImpressionPanelProps) {
  const { t } = useTranslation('report');
  const { t: tCommon } = useTranslation('common');
  const [isEditing, setIsEditing] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const hasInferenceResult = Boolean(
    inferenceSummary ||
    inferenceStatus ||
    inferenceModelVersion ||
    inferenceConfidence !== undefined ||
    inferenceCompletedAt
  );

  const resolvedInferenceStatus = inferenceStatus || (inferenceSummary ? 'finished' : undefined);
  const inferenceStatusLabel: Record<string, { label: string; className: string }> = {
    queued: { label: t('ai.status.queued'), className: 'bg-warning/10 text-warning border-warning/30' },
    started: { label: t('ai.status.running'), className: 'bg-info/10 text-info border-info/30' },
    finished: { label: t('ai.status.completed'), className: 'bg-success/10 text-success border-success/30' },
    failed: { label: t('ai.status.failed'), className: 'bg-destructive/10 text-destructive border-destructive/30' },
  };

  // Auto-generate impression when findings change and we haven't generated yet
  useEffect(() => {
    if (findings && findings.length > 50 && !impression && !hasAutoGenerated && !isGenerating) {
      const timer = setTimeout(() => {
        setHasAutoGenerated(true);
        onGenerateImpression();
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [findings, impression, hasAutoGenerated, isGenerating, onGenerateImpression]);

  const handleSave = useCallback(() => {
    setIsEditing(false);
  }, []);

  const handleRegenerate = useCallback(() => {
    onGenerateImpression();
  }, [onGenerateImpression]);

  const canApprove = impression && qaStatus !== 'fail' && !isGenerating;

  return (
    <div className="flex flex-col flex-1">
      {/* Header */}
      <div className="panel-header">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-semibold uppercase tracking-wide">{t('impression.title')}</h3>
          <Badge variant="outline" className="bg-primary/10 text-primary border-primary/30 text-xs">
            <Sparkles className="h-3 w-3 mr-1" />
            {t('impression.aiDraft')}
          </Badge>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => isEditing ? handleSave() : setIsEditing(true)}
          disabled={isGenerating}
        >
          {isEditing ? (
            <>
              <Save className="h-4 w-4 mr-1.5" />
              {tCommon('actions.save')}
            </>
          ) : (
            <>
              <Edit3 className="h-4 w-4 mr-1.5" />
              {tCommon('actions.edit')}
            </>
          )}
        </Button>
      </div>

      {/* QA Status */}
      <div className="px-4 py-2 border-b border-border flex items-center justify-between bg-panel-secondary/30">
        <StatusBadge status={qaStatus} size="sm" />
        {isGenerating && (
          <span className="text-xs text-muted-foreground flex items-center gap-1.5">
            <div className="w-3 h-3 border-2 border-primary border-t-transparent rounded-full spinner" />
            {t('impression.generating')}
          </span>
        )}
      </div>

      {/* QA Warnings */}
      {qaWarnings.length > 0 && (
        <div className="px-4 py-2 bg-warning/5 border-b border-warning/20 space-y-1">
          {qaWarnings.map((warning, idx) => (
            <div key={idx} className="flex items-start gap-2 text-xs text-warning">
              <AlertTriangle className="h-3 w-3 mt-0.5 shrink-0" />
              <span>{warning}</span>
            </div>
          ))}
        </div>
      )}

      {/* Inference Result */}
      {hasInferenceResult && (
        <div className="px-4 py-2 border-b border-border bg-panel-secondary/20 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              {t('inference.title')}
            </span>
            {resolvedInferenceStatus && inferenceStatusLabel[resolvedInferenceStatus] && (
              <Badge
                variant="outline"
                className={cn('text-[10px] px-1.5 py-0', inferenceStatusLabel[resolvedInferenceStatus].className)}
              >
                {inferenceStatusLabel[resolvedInferenceStatus].label}
              </Badge>
            )}
          </div>
          <div className="text-xs text-muted-foreground space-y-1">
            <div>{t('inference.modelVersion', { version: inferenceModelVersion || 'n/a' })}</div>
            {inferenceConfidence !== undefined && (
              <div>{t('inference.confidence', { value: Math.round(inferenceConfidence * 100) })}</div>
            )}
            {inferenceCompletedAt && (
              <div>
                {t('inference.completedAt', { time: `${formatDate(inferenceCompletedAt)} ${formatTime(inferenceCompletedAt)}` })}
              </div>
            )}
            {inferenceJobId && (
              <div>Job: {inferenceJobId.slice(0, 8)}...</div>
            )}
          </div>
          {inferenceSummary ? (
            <p className="text-sm text-foreground whitespace-pre-wrap">{inferenceSummary}</p>
          ) : (
            <p className="text-xs text-muted-foreground">{t('inference.summary')}: -</p>
          )}
          {inferenceImageRefs && inferenceImageRefs.length > 0 && (
            <div className="border-t border-border pt-2">
              <div className="text-[10px] uppercase tracking-wide text-muted-foreground mb-1">
                {t('inference.evidence', { count: inferenceImageRefs.length })}
              </div>
              <div className="space-y-1">
                {inferenceImageRefs.map((ref) => (
                  <Button
                    key={`${ref.instanceId}-${ref.frameIndex}-${ref.stackIndex}`}
                    variant="ghost"
                    size="sm"
                    className="h-auto w-full justify-start px-2 py-1 text-xs"
                    onClick={() => onEvidenceSelect?.(ref)}
                    disabled={!onEvidenceSelect}
                  >
                    <span className="truncate">
                      {ref.instanceId.slice(0, 8)}… · {t('inference.frame', { frame: ref.frameIndex })}
                    </span>
                  </Button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-hidden min-h-[200px]">
        {isEditing ? (
          <ReportEditor
            value={impression}
            onChange={onImpressionChange}
            placeholder={t('impression.placeholder')}
            className="h-full min-h-[200px]"
            ariaLabel={t('impression.title')}
          />
        ) : (
          <div className="h-full p-4 overflow-y-auto">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center h-full gap-4 text-muted-foreground">
                <div className="w-8 h-8 border-3 border-primary border-t-transparent rounded-full spinner" />
                <p className="text-sm">{t('impression.generating')}</p>
              </div>
            ) : impression ? (
              <p className="text-sm whitespace-pre-wrap leading-relaxed">{impression}</p>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                {t('impression.autoGenerated')}
              </p>
            )}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-border bg-panel-secondary/30 space-y-2">
        <div className="flex items-center justify-between gap-3 rounded-md border border-border bg-card px-3 py-2 text-xs">
          <div>
            <div className="font-medium text-foreground">{t('inference.useAllFrames')}</div>
            <div className="text-muted-foreground">{t('inference.useAllFramesHelp')}</div>
          </div>
          <Switch
            checked={Boolean(useAllFrames)}
            onCheckedChange={(value) => onUseAllFramesChange?.(value)}
            disabled={!onUseAllFramesChange || isGenerating}
          />
        </div>
        <ApprovalDialog
          onConfirm={onApprove}
          disabled={!canApprove}
          triggerLabel={t('approval.approve')}
        />

        {onExportSr && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="w-full justify-between"
                disabled={!impression && !findings}
              >
                <span className="flex items-center">
                  <Download className="h-4 w-4 mr-1.5" />
                  {t('export.dicomSr')}
                </span>
                <ChevronDown className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-48">
              <DropdownMenuItem onClick={() => onExportSr('dicom')}>
                DICOM SR (Binary)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => onExportSr('json')}>
                DICOM SR (JSON)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}
        
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            className="flex-1"
            onClick={handleRegenerate}
            disabled={isGenerating || !findings}
          >
            <Sparkles className="h-4 w-4 mr-1.5" />
            {t('impression.regenerate')}
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="flex-1"
            onClick={handleSave}
            disabled={!impression}
          >
            <Save className="h-4 w-4 mr-1.5" />
            {tCommon('actions.save')}
          </Button>
        </div>
      </div>

      {/* Footer hint */}
      <div className="px-4 py-2 border-t border-border text-xs text-muted-foreground text-center">
        {t('impression.approveHint')}
      </div>
    </div>
  );
}
